In [ ]:
from bs4 import BeautifulSoup as bs
import requests
import os
import pandas as pd
import json

In [2]:
url = "https://www.usatoday.com/story/news/nation-now/2017/08/30/these-most-popular-cars-and-trucks-every-state/478537001/"

response = requests.get(url)

soup = bs(response.text,'html.parser')

In [3]:
results = soup.find_all('p', class_="p-text")

results[6].text

'Alaska:\xa0F150'

In [4]:
states_cars = [] 
for result in results:
    try:
        state_car = result.text
        states_cars.append(state_car)
        print(state_car)
    except AttributeError as e:
        print(e)

Ford's F150 is America's best selling vehicle, but the pick-up truck doesn't reign supreme in all 50 states.
According to Kelley Blue Book data, more than 10 states choose SUVs over pickups. Compact cars (Honda's Civic, Toyota's Corolla and Yaris) are the top picks in California, Ohio, Florida, Washington, D.C. and Puerto Rico.
Still, Kelley Blue Book's list of the most popular vehicles sold in each state based on new car registrations in 2016 shows Americans love their trucks.
This year, the F-Series remains most popular, but Tim Fleming, analyst for Kelley Blue Book said 2017 consumers could shift last year's data.
"Sedans are rapidly falling out of favor," Fleming said in an email. "The Camry, Civic and Corolla have dropped from the fourth, fifth and sixth places to seventh, eighth and ninth this year. We don’t see this trend stopping any time soon, although the new Camry could boost sales in the short-term."
Here's a look at the 2016 data:
Alaska: F150
Alabama: F150
Arizona: F150
Arkansas: Sierra 1500
California: Civic
Colorado: Outback
Connecticut: Rogue
Washington, D.C.: Civic
Delaware: Silverado 1500
Florida: Corolla
Georgia: F150
Hawaii: Tacoma
Iowa: Silverado 1500
Idaho: F150
Illinois: CR-V
Indiana: Silverado 1500
Kansas: F150
Kentucky: F150
Louisiana: F150
Massachusetts: RAV4
Maryland: CR-V
Maine: Silverado 1500
Michigan: Escape
Minnesota: F150
Missouri: F150
Mississippi: F150
Montana: F150
North Carolina: Accord
North Dakota: F150
Nebraska: F150
New Hampshire: Silverado 1500
New Jersey: CR-V
New Mexico: F150
Nevada: RAV4
New York: Rogue
Ohio: Civic
Oklahoma: F150
Oregon: Outback
Pennsylvania: CR-V
Puerto Rico: Yaris
Rhode Island: RAV4
South Carolina: F150
South Dakota: F150
Tennessee: F150
Texas: F150
Utah: F150
Virginia: CR-V
Vermont: RAV4
Washington: Outback
Wisconsin: Silverado 1500
West Virginia: Silverado 1500
Wyoming: F150
Follow Ashley May on Twitter: @AshleyMayTweets

In [5]:
states_cars = states_cars[6:58]

In [6]:
df = pd.DataFrame({
    "States_and_Cars":states_cars
})

df.head()

         States_and_Cars
0           Alaska: F150
1          Alabama: F150
2          Arizona: F150
3  Arkansas: Sierra 1500
4      California: Civic

In [7]:
df=df['States_and_Cars'].str.split(":", n=2, expand = True)

df.rename(columns = {0:'State',1:'Model'},inplace=True)

df.head()

        State         Model
0      Alaska          F150
1     Alabama          F150
2     Arizona          F150
3    Arkansas   Sierra 1500
4  California         Civic

In [8]:
car_list = []
item = 0

for i in range(len(df['Model'])):
    car = df['Model'][i].replace(u'\xa0',u' ').lstrip().rstrip().replace(' ', '-').replace('F150', 'F-150')
    car_list.append(car)
    
set(car_list)

{'Accord',
 'CR-V',
 'Civic',
 'Corolla',
 'Escape',
 'F-150',
 'Outback',
 'RAV4',
 'Rogue',
 'Sierra-1500',
 'Silverado-1500',
 'Tacoma',
 'Yaris'}

In [9]:
df['Model'] = car_list

df.head()

        State        Model
0      Alaska        F-150
1     Alabama        F-150
2     Arizona        F-150
3    Arkansas  Sierra-1500
4  California        Civic

In [10]:
df['Make'] = df['Model'].map({
    'Accord' : 'Honda',
    'CR-V' : 'Honda',
    'Civic' : 'Honda',
    'Corolla' : 'Toyota',
    'Escape' : 'Ford',
    'F-150' : 'Ford',
    'Outback' : 'Subaru',
    'RAV4' : 'Toyota',
    'Rogue' : 'Nissan',
    'Sierra-1500' : 'GMC',
    'Silverado-1500' : 'Chevrolet',
    'Tacoma' : 'Toyota',
    'Yaris' : 'Toyota'})

df.head()

        State        Model   Make
0      Alaska        F-150   Ford
1     Alabama        F-150   Ford
2     Arizona        F-150   Ford
3    Arkansas  Sierra-1500    GMC
4  California        Civic  Honda

In [11]:
unique_cars_df = df[['Model','Make']]

unique_cars_df = unique_cars_df.drop_duplicates(subset='Model')

unique_cars_df.reset_index(drop=True, inplace=True)

unique_cars_df

             Model       Make
0            F-150       Ford
1      Sierra-1500        GMC
2            Civic      Honda
3          Outback     Subaru
4            Rogue     Nissan
5   Silverado-1500  Chevrolet
6          Corolla     Toyota
7           Tacoma     Toyota
8             CR-V      Honda
9             RAV4     Toyota
10          Escape       Ford
11          Accord      Honda
12           Yaris     Toyota

# Scrape Motor Trend for Vehicle Information

In [13]:
car_response = []
car_soup = []

#https://www.motortrend.com/cars/chevrolet/silverado-1500/2019/

for item in range(len(unique_cars_df['Model'])):
    car_url = "https://www.motortrend.com/cars/" + unique_cars_df['Make'][item] + "/" + unique_cars_df['Model'][item] + \
    "/2016/" 
    print(car_url)
    responses = requests.get(car_url)
    car_soup.append(bs(responses.text,'html.parser'))
    car_response.append(responses)
    print(responses)

https://www.motortrend.com/cars/Ford/F-150/2016/
<Response [200]>
https://www.motortrend.com/cars/GMC/Sierra-1500/2016/
<Response [200]>
https://www.motortrend.com/cars/Honda/Civic/2016/
<Response [200]>
https://www.motortrend.com/cars/Subaru/Outback/2016/
<Response [200]>
https://www.motortrend.com/cars/Nissan/Rogue/2016/
<Response [200]>
https://www.motortrend.com/cars/Chevrolet/Silverado-1500/2016/
<Response [200]>
https://www.motortrend.com/cars/Toyota/Corolla/2016/
<Response [200]>
https://www.motortrend.com/cars/Toyota/Tacoma/2016/
<Response [200]>
https://www.motortrend.com/cars/Honda/CR-V/2016/
<Response [200]>
https://www.motortrend.com/cars/Toyota/RAV4/2016/
<Response [200]>
https://www.motortrend.com/cars/Ford/Escape/2016/
<Response [200]>
https://www.motortrend.com/cars/Honda/Accord/2016/
<Response [200]>
https://www.motortrend.com/cars/Toyota/Yaris/2016/
<Response [200]>

In [14]:
car_soup[0].find_all('div', class_ = "key")[1:12]

[<div class="key">Value Rating</div>,
 <div class="key">Engine Name</div>,
 <div class="key">Transmission Name</div>,
 <div class="key">Trim</div>,
 <div class="key">Class</div>,
 <div class="key">Horsepower</div>,
 <div class="key">Standard MPG</div>,
 <div class="key">Body Style</div>,
 <div class="key">Drivetrain</div>,
 <div class="key">Fuel Type</div>,
 <div class="key">Seating Capacity (Std/Max)</div>]

In [15]:
car_soup[0].find_all('div', class_ = "value")[1:12]

[<div class="value">Below Average</div>,
 <div class="value">Engine: V6 Flex Fuel 3.5 Liter</div>,
 <div class="value"><span itemprop="vehicleTransmission">SelectShift® 6 Speed Automatic Mode Select with Manual Mode (6R80E)</span></div>,
 <div class="value"><span itemprop="vehicleConfiguration">XL 2WD Short Bed Regular Cab</span></div>,
 <div class="value">Full-Size Pickup LD</div>,
 <div class="value">283@6500</div>,
 <div class="value"><div itemprop="fuelEfficiency" itemscope="" itemtype="//schema.org/QuantitativeValue">
 <span itemprop="minValue">18</span> City /
 									  <span itemprop="maxValue">24</span> Hwy</div></div>,
 <div class="value"><span itemprop="bodyType">Truck</span></div>,
 <div class="value"><span itemprop="driveWheelConfiguration">RWD</span></div>,
 <div class="value"><span itemprop="fuelType">Unleaded Regular</span></div>,
 <div class="value"><span itemprop="vehicleSeatingCapacity">3/3</span></div>]

In [16]:
car_soup[0]('div', class_="price")[2].text

'$21,610'

In [17]:
MSRP = []
CPO = []
UCV = []
VR = []
EN = []
TN = []
T = []
C = []
HP = []
MPG = []
BSt = []
DT = []
FT = []
SC = []
IMGURL = []

for item in car_soup:
    #Retreive Pricing Information from Price Tags
    msr = item.find_all('div', class_="price")[0].text
    try:
        cp = item.find_all('div', class_="price")[1].text        
    except:
        cp = "N/A"
    try:
        uc = item.find_all('div', class_="price")[2].text        
    except:
        uc = "N/A"
    MSRP.append(msr)
    CPO.append(cp)
    UCV.append(uc)
    
    #Retreive Specification Information from Key Value pair tags
    aV = item.find_all('div', class_ = "value")[1].text
    aE = item.find_all('div', class_ = "value")[2].text
    aTN = item.find_all('div', class_ = "value")[3].text
    aT = item.find_all('div', class_ = "value")[4].text
    aC = item.find_all('div', class_ = "value")[5].text
    aHP = item.find_all('div', class_ = "value")[6].text
    aMPG = item.find_all('div', class_ = "value")[7].text
    aBSt = item.find_all('div', class_ = "value")[8].text
    aDT = item.find_all('div', class_ = "value")[9].text
    aFT = item.find_all('div', class_ = "value")[10].text
    aSC = item.find_all('div', class_ = "value")[11].text
    IU = item.find('img', class_ = "attachment-full-width")['data-base']
    
    VR.append(aV)
    EN.append(aE)
    TN.append(aTN)
    T.append(aT)
    C.append(aC)
    HP.append(aHP)
    MPG.append(aMPG.replace('\n', '').replace('\t\t\t\t\t\t\t\t\t ', ''))
    BSt.append(aBSt)
    DT.append(aDT)
    FT.append(aFT)
    SC.append(aSC)
    IMGURL.append(IU)
    
    print(MSRP)
    print(CPO)
    print(UCV)
    print(VR)
    print(EN)
    print(TN)
    print(T)
    print(C)
    print(HP)
    print(MPG)
    print(BSt)
    print(DT)
    print(FT)
    print(SC)
    print(IU)

['$26,540']
['$23,900']
['$21,610']
['Below Average']
['Engine: V6 Flex Fuel 3.5 Liter']
['SelectShift® 6 Speed Automatic Mode Select with Manual Mode (6R80E)']
['XL 2WD Short Bed Regular Cab']
['Full-Size Pickup LD']
['283@6500']
['18 City / 24 Hwy']
['Truck']
['RWD']
['Unleaded Regular']
['3/3']
https://st.motortrend.com/uploads/sites/10/2017/11/2018-ford-f-150-xlt-supercab-pick-up-angular-front.png
['$26,540', '$27,815']
['$23,900', '$20,350']
['$21,610', '$18,685']
['Below Average', 'Excellent']
['Engine: V6 Flex Fuel 3.5 Liter', 'Engine: V6 Flex Fuel 4.3 Liter EcoTec3']
['SelectShift® 6 Speed Automatic Mode Select with Manual Mode (6R80E)', 'Hydra-Matic 6 Speed Automatic Mode Select (6L80)']
['XL 2WD Short Bed Regular Cab', 'Base 2WD Standard Bed Regular Cab']
['Full-Size Pickup LD', 'Full-Size Pickup LD']
['283@6500', '285@5300']
['18 City / 24 Hwy', '18 City / 23 Hwy']
['Truck', 'Truck']
['RWD', 'RWD']
['Unleaded Regular', 'Unleaded Regular']
['3/3', '3/2']
https://st.motortrend.com/uploads/sites/10/2018/03/2019-GMC-Sierra-1500-Denali-front-view.jpg
['$26,540', '$27,815', '$18,640']
['$23,900', '$20,350', '$18,640']
['$21,610', '$18,685', 'N/A']
['Below Average', 'Excellent', 'N/A']
['Engine: V6 Flex Fuel 3.5 Liter', 'Engine: V6 Flex Fuel 4.3 Liter EcoTec3', 'Engine: 4-Cyl 2.0 Liter']
['SelectShift® 6 Speed Automatic Mode Select with Manual Mode (6R80E)', 'Hydra-Matic 6 Speed Automatic Mode Select (6L80)', '6 Speed Manual']
['XL 2WD Short Bed Regular Cab', 'Base 2WD Standard Bed Regular Cab', 'LX (Manual) Sedan']
['Full-Size Pickup LD', 'Full-Size Pickup LD', 'Compact Passenger Car']
['283@6500', '285@5300', '158@6500']
['18 City / 24 Hwy', '18 City / 23 Hwy', '27 City / 38 Hwy']
['Truck', 'Truck', 'Sedan']
['RWD', 'RWD', 'FWD']
['Unleaded Regular', 'Unleaded Regular', 'Unleaded Regular']
['3/3', '3/2', '5/5']
https://st.motortrend.com/uploads/sites/10/2018/08/2019-Honda-Civic-Coupe-Sport.jpg
['$26,540', '$27,815', '$18,640', '$24,995']
['$23,900', '$20,350', '$18,640', '$19,175']
['$21,610', '$18,685', 'N/A', '$17,890']
['Below Average', 'Excellent', 'N/A', 'Average']
['Engine: V6 Flex Fuel 3.5 Liter', 'Engine: V6 Flex Fuel 4.3 Liter EcoTec3', 'Engine: 4-Cyl 2.0 Liter', 'Engine: 4-Cyl 2.5 Liter BOXER']
['SelectShift® 6 Speed Automatic Mode Select with Manual Mode (6R80E)', 'Hydra-Matic 6 Speed Automatic Mode Select (6L80)', '6 Speed Manual', 'Lineartronic CVT Continuously Variable Automatic Mode Select with Manual Mode']
['XL 2WD Short Bed Regular Cab', 'Base 2WD Standard Bed Regular Cab', 'LX (Manual) Sedan', '2.5i Wagon']
['Full-Size Pickup LD', 'Full-Size Pickup LD', 'Compact Passenger Car', 'Mid-Size Utility']
['283@6500', '285@5300', '158@6500', '175@5800']
['18 City / 24 Hwy', '18 City / 23 Hwy', '27 City / 38 Hwy', '25 City / 32 Hwy']
['Truck', 'Truck', 'Sedan', 'Wagon']
['RWD', 'RWD', 'FWD', 'AWD']
['Unleaded Regular', 'Unleaded Regular', 'Unleaded Regular', 'Unleaded Regular']
['3/3', '3/2', '5/5', '5/5']
https://st.motortrend.com/uploads/sites/10/2017/10/2018-subaru-outback-premium-wagon-angular-front.png
['$26,540', '$27,815', '$18,640', '$24,995', '$23,330']
['$23,900', '$20,350', '$18,640', '$19,175', '$16,225']
['$21,610', '$18,685', 'N/A', '$17,890', '$15,115']
['Below Average', 'Excellent', 'N/A', 'Average', 'Average']
['Engine: V6 Flex Fuel 3.5 Liter', 'Engine: V6 Flex Fuel 4.3 Liter EcoTec3', 'Engine: 4-Cyl 2.0 Liter', 'Engine: 4-Cyl 2.5 Liter BOXER', 'Engine: 4-Cyl 2.5 Liter']
['SelectShift® 6 Speed Automatic Mode Select with Manual Mode (6R80E)', 'Hydra-Matic 6 Speed Automatic Mode Select (6L80)', '6 Speed Manual', 'Lineartronic CVT Continuously Variable Automatic Mode Select with Manual Mode', 'Xtronic Continuously Variable Automatic Mode Select']
['XL 2WD Short Bed Regular Cab', 'Base 2WD Standard Bed Regular Cab', 'LX (Manual) Sedan', '2.5i Wagon', 'S 2WD']
['Full-Size Pickup LD', 'Full-Size Pickup LD', 'Compact Passenger Car', 'Mid-Size Utility', 'Compact Utility']
['283@6500', '285@5300', '158@6500', '175@5800', '170@6000']
['18 City / 24 Hwy', '18 City / 23 Hwy', '27 City / 38 Hwy', '25 City / 32 Hwy', '26 City / 32 Hwy']
['Truck', 'Truck', 'Sedan', 'Wagon', 'SUV/Crossover']
['RWD', 'RWD', 'FWD', 'AWD', 'FWD']
['Unleaded Regular', 'Unleaded Regular', 'Unleaded Regular', 'Unleaded Regular', 'Unleaded Regular']
['3/3', '3/2', '5/5', '5/5', '5/7']
https://st.motortrend.com/uploads/sites/10/2017/12/2018-nissan-rogue-s-suv-angular-front.png
['$26,540', '$27,815', '$18,640', '$24,995', '$23,330', '$27,095']
['$23,900', '$20,350', '$18,640', '$19,175', '$16,225', '$20,000']
['$21,610', '$18,685', 'N/A', '$17,890', '$15,115', '$18,435']
['Below Average', 'Excellent', 'N/A', 'Average', 'Average', 'Excellent']
['Engine: V6 Flex Fuel 3.5 Liter', 'Engine: V6 Flex Fuel 4.3 Liter EcoTec3', 'Engine: 4-Cyl 2.0 Liter', 'Engine: 4-Cyl 2.5 Liter BOXER', 'Engine: 4-Cyl 2.5 Liter', 'Engine: V6 Flex Fuel 4.3 Liter EcoTec3']
['SelectShift® 6 Speed Automatic Mode Select with Manual Mode (6R80E)', 'Hydra-Matic 6 Speed Automatic Mode Select (6L80)', '6 Speed Manual', 'Lineartronic CVT Continuously Variable Automatic Mode Select with Manual Mode', 'Xtronic Continuously Variable Automatic Mode Select', 'Hydra-Matic 6 Speed Automatic Mode Select with Manual Mode (6L80)']
['XL 2WD Short Bed Regular Cab', 'Base 2WD Standard Bed Regular Cab', 'LX (Manual) Sedan', '2.5i Wagon', 'S 2WD', 'Work Truck 1WT 2WD Standard Bed Regular Cab']
['Full-Size Pickup LD', 'Full-Size Pickup LD', 'Compact Passenger Car', 'Mid-Size Utility', 'Compact Utility', 'Full-Size Pickup LD']
['283@6500', '285@5300', '158@6500', '175@5800', '170@6000', '285@5300']
['18 City / 24 Hwy', '18 City / 23 Hwy', '27 City / 38 Hwy', '25 City / 32 Hwy', '26 City / 32 Hwy', '18 City / 23 Hwy']
['Truck', 'Truck', 'Sedan', 'Wagon', 'SUV/Crossover', 'Truck']
['RWD', 'RWD', 'FWD', 'AWD', 'FWD', 'RWD']
['Unleaded Regular', 'Unleaded Regular', 'Unleaded Regular', 'Unleaded Regular', 'Unleaded Regular', 'Unleaded Regular']
['3/3', '3/2', '5/5', '5/5', '5/7', '3/5']
https://st.motortrend.com/uploads/sites/10/2018/01/2019-Chevrolet-Silverado-1500-front-side-view-1.jpg
['$26,540', '$27,815', '$18,640', '$24,995', '$23,330', '$27,095', '$17,300']
['$23,900', '$20,350', '$18,640', '$19,175', '$16,225', '$20,000', '$17,300']
['$21,610', '$18,685', 'N/A', '$17,890', '$15,115', '$18,435', 'N/A']
['Below Average', 'Excellent', 'N/A', 'Average', 'Average', 'Excellent', 'N/A']
['Engine: V6 Flex Fuel 3.5 Liter', 'Engine: V6 Flex Fuel 4.3 Liter EcoTec3', 'Engine: 4-Cyl 2.0 Liter', 'Engine: 4-Cyl 2.5 Liter BOXER', 'Engine: 4-Cyl 2.5 Liter', 'Engine: V6 Flex Fuel 4.3 Liter EcoTec3', 'Engine: 4-Cyl 1.8 Liter']
['SelectShift® 6 Speed Automatic Mode Select with Manual Mode (6R80E)', 'Hydra-Matic 6 Speed Automatic Mode Select (6L80)', '6 Speed Manual', 'Lineartronic CVT Continuously Variable Automatic Mode Select with Manual Mode', 'Xtronic Continuously Variable Automatic Mode Select', 'Hydra-Matic 6 Speed Automatic Mode Select with Manual Mode (6L80)', '6 Speed Manual']
['XL 2WD Short Bed Regular Cab', 'Base 2WD Standard Bed Regular Cab', 'LX (Manual) Sedan', '2.5i Wagon', 'S 2WD', 'Work Truck 1WT 2WD Standard Bed Regular Cab', 'L (Manual) Sedan']
['Full-Size Pickup LD', 'Full-Size Pickup LD', 'Compact Passenger Car', 'Mid-Size Utility', 'Compact Utility', 'Full-Size Pickup LD', 'Compact Passenger Car']
['283@6500', '285@5300', '158@6500', '175@5800', '170@6000', '285@5300', '132@6000']
['18 City / 24 Hwy', '18 City / 23 Hwy', '27 City / 38 Hwy', '25 City / 32 Hwy', '26 City / 32 Hwy', '18 City / 23 Hwy', '28 City / 36 Hwy']
['Truck', 'Truck', 'Sedan', 'Wagon', 'SUV/Crossover', 'Truck', 'Sedan']
['RWD', 'RWD', 'FWD', 'AWD', 'FWD', 'RWD', 'FWD']
['Unleaded Regular', 'Unleaded Regular', 'Unleaded Regular', 'Unleaded Regular', 'Unleaded Regular', 'Unleaded Regular', 'Unleaded Regular']
['3/3', '3/2', '5/5', '5/5', '5/7', '3/5', '5/5']
https://st.motortrend.com/uploads/sites/10/2017/10/2018-toyota-corolla-l-sedan-angular-front.png
['$26,540', '$27,815', '$18,640', '$24,995', '$23,330', '$27,095', '$17,300', '$23,660']
['$23,900', '$20,350', '$18,640', '$19,175', '$16,225', '$20,000', '$17,300', '$20,000']
['$21,610', '$18,685', 'N/A', '$17,890', '$15,115', '$18,435', 'N/A', '$18,501']
['Below Average', 'Excellent', 'N/A', 'Average', 'Average', 'Excellent', 'N/A', 'Excellent']
['Engine: V6 Flex Fuel 3.5 Liter', 'Engine: V6 Flex Fuel 4.3 Liter EcoTec3', 'Engine: 4-Cyl 2.0 Liter', 'Engine: 4-Cyl 2.5 Liter BOXER', 'Engine: 4-Cyl 2.5 Liter', 'Engine: V6 Flex Fuel 4.3 Liter EcoTec3', 'Engine: 4-Cyl 1.8 Liter', 'Engine: 4-Cyl 2.7 Liter']
['SelectShift® 6 Speed Automatic Mode Select with Manual Mode (6R80E)', 'Hydra-Matic 6 Speed Automatic Mode Select (6L80)', '6 Speed Manual', 'Lineartronic CVT Continuously Variable Automatic Mode Select with Manual Mode', 'Xtronic Continuously Variable Automatic Mode Select', 'Hydra-Matic 6 Speed Automatic Mode Select with Manual Mode (6L80)', '6 Speed Manual', 'ECT-i 6 Speed Automatic Mode Select with Manual Mode']
['XL 2WD Short Bed Regular Cab', 'Base 2WD Standard Bed Regular Cab', 'LX (Manual) Sedan', '2.5i Wagon', 'S 2WD', 'Work Truck 1WT 2WD Standard Bed Regular Cab', 'L (Manual) Sedan', 'SR 2WD Access Cab']
['Full-Size Pickup LD', 'Full-Size Pickup LD', 'Compact Passenger Car', 'Mid-Size Utility', 'Compact Utility', 'Full-Size Pickup LD', 'Compact Passenger Car', 'Mid-Size Pickup']
['283@6500', '285@5300', '158@6500', '175@5800', '170@6000', '285@5300', '132@6000', '159@5200']
['18 City / 24 Hwy', '18 City / 23 Hwy', '27 City / 38 Hwy', '25 City / 32 Hwy', '26 City / 32 Hwy', '18 City / 23 Hwy', '28 City / 36 Hwy', '19 City / 23 Hwy']
['Truck', 'Truck', 'Sedan', 'Wagon', 'SUV/Crossover', 'Truck', 'Sedan', 'Truck']
['RWD', 'RWD', 'FWD', 'AWD', 'FWD', 'RWD', 'FWD', 'RWD']
['Unleaded Regular', 'Unleaded Regular', 'Unleaded Regular', 'Unleaded Regular', 'Unleaded Regular', 'Unleaded Regular', 'Unleaded Regular', 'Unleaded Regular']
['3/3', '3/2', '5/5', '5/5', '5/7', '3/5', '5/5', '4/2']
https://st.motortrend.com/uploads/sites/10/2019/02/2020-Toyota-Tacoma-TRD-Off-Road-1.jpg

['$26,540', '$27,815', '$18,640', '$24,995', '$23,330', '$27,095', '$17,300', '$23,660', '$23,845']
['$23,900', '$20,350', '$18,640', '$19,175', '$16,225', '$20,000', '$17,300', '$20,000', '$17,075']
['$21,610', '$18,685', 'N/A', '$17,890', '$15,115', '$18,435', 'N/A', '$18,501', '$15,876']
['Below Average', 'Excellent', 'N/A', 'Average', 'Average', 'Excellent', 'N/A', 'Excellent', 'Excellent']
['Engine: V6 Flex Fuel 3.5 Liter', 'Engine: V6 Flex Fuel 4.3 Liter EcoTec3', 'Engine: 4-Cyl 2.0 Liter', 'Engine: 4-Cyl 2.5 Liter BOXER', 'Engine: 4-Cyl 2.5 Liter', 'Engine: V6 Flex Fuel 4.3 Liter EcoTec3', 'Engine: 4-Cyl 1.8 Liter', 'Engine: 4-Cyl 2.7 Liter', 'Engine: 4-Cyl 2.4 Liter Earth Dreams Technology™']
['SelectShift® 6 Speed Automatic Mode Select with Manual Mode (6R80E)', 'Hydra-Matic 6 Speed Automatic Mode Select (6L80)', '6 Speed Manual', 'Lineartronic CVT Continuously Variable Automatic Mode Select with Manual Mode', 'Xtronic Continuously Variable Automatic Mode Select', 'Hydra-Matic 6 Speed Automatic Mode Select with Manual Mode (6L80)', '6 Speed Manual', 'ECT-i 6 Speed Automatic Mode Select with Manual Mode', 'Continuously Variable Automatic Mode Select']
['XL 2WD Short Bed Regular Cab', 'Base 2WD Standard Bed Regular Cab', 'LX (Manual) Sedan', '2.5i Wagon', 'S 2WD', 'Work Truck 1WT 2WD Standard Bed Regular Cab', 'L (Manual) Sedan', 'SR 2WD Access Cab', 'LX 2WD']
['Full-Size Pickup LD', 'Full-Size Pickup LD', 'Compact Passenger Car', 'Mid-Size Utility', 'Compact Utility', 'Full-Size Pickup LD', 'Compact Passenger Car', 'Mid-Size Pickup', 'Mid-Size Utility']
['283@6500', '285@5300', '158@6500', '175@5800', '170@6000', '285@5300', '132@6000', '159@5200', '185@6400']
['18 City / 24 Hwy', '18 City / 23 Hwy', '27 City / 38 Hwy', '25 City / 32 Hwy', '26 City / 32 Hwy', '18 City / 23 Hwy', '28 City / 36 Hwy', '19 City / 23 Hwy', '26 City / 32 Hwy']
['Truck', 'Truck', 'Sedan', 'Wagon', 'SUV/Crossover', 'Truck', 'Sedan', 'Truck', 'SUV/Crossover']
['RWD', 'RWD', 'FWD', 'AWD', 'FWD', 'RWD', 'FWD', 'RWD', 'FWD']
['Unleaded Regular', 'Unleaded Regular', 'Unleaded Regular', 'Unleaded Regular', 'Unleaded Regular', 'Unleaded Regular', 'Unleaded Regular', 'Unleaded Regular', 'Unleaded Regular']
['3/3', '3/2', '5/5', '5/5', '5/7', '3/5', '5/5', '4/2', '5/5']
https://st.motortrend.com/uploads/sites/10/2017/10/2018-Honda-CR-V-front-three-quarter-in-motion-01.jpg
['$26,540', '$27,815', '$18,640', '$24,995', '$23,330', '$27,095', '$17,300', '$23,660', '$23,845', '$24,350']
['$23,900', '$20,350', '$18,640', '$19,175', '$16,225', '$20,000', '$17,300', '$20,000', '$17,075', '$18,675']
['$21,610', '$18,685', 'N/A', '$17,890', '$15,115', '$18,435', 'N/A', '$18,501', '$15,876', '$17,401']
['Below Average', 'Excellent', 'N/A', 'Average', 'Average', 'Excellent', 'N/A', 'Excellent', 'Excellent', 'Excellent']
['Engine: V6 Flex Fuel 3.5 Liter', 'Engine: V6 Flex Fuel 4.3 Liter EcoTec3', 'Engine: 4-Cyl 2.0 Liter', 'Engine: 4-Cyl 2.5 Liter BOXER', 'Engine: 4-Cyl 2.5 Liter', 'Engine: V6 Flex Fuel 4.3 Liter EcoTec3', 'Engine: 4-Cyl 1.8 Liter', 'Engine: 4-Cyl 2.7 Liter', 'Engine: 4-Cyl 2.4 Liter Earth Dreams Technology™', 'Engine: 4-Cyl 2.5 Liter']
['SelectShift® 6 Speed Automatic Mode Select with Manual Mode (6R80E)', 'Hydra-Matic 6 Speed Automatic Mode Select (6L80)', '6 Speed Manual', 'Lineartronic CVT Continuously Variable Automatic Mode Select with Manual Mode', 'Xtronic Continuously Variable Automatic Mode Select', 'Hydra-Matic 6 Speed Automatic Mode Select with Manual Mode (6L80)', '6 Speed Manual', 'ECT-i 6 Speed Automatic Mode Select with Manual Mode', 'Continuously Variable Automatic Mode Select', 'ECT-i 6 Speed Automatic Mode Select with Manual Mode']
['XL 2WD Short Bed Regular Cab', 'Base 2WD Standard Bed Regular Cab', 'LX (Manual) Sedan', '2.5i Wagon', 'S 2WD', 'Work Truck 1WT 2WD Standard Bed Regular Cab', 'L (Manual) Sedan', 'SR 2WD Access Cab', 'LX 2WD', 'LE FWD']
['Full-Size Pickup LD', 'Full-Size Pickup LD', 'Compact Passenger Car', 'Mid-Size Utility', 'Compact Utility', 'Full-Size Pickup LD', 'Compact Passenger Car', 'Mid-Size Pickup', 'Mid-Size Utility', 'Mid-Size Utility']
['283@6500', '285@5300', '158@6500', '175@5800', '170@6000', '285@5300', '132@6000', '159@5200', '185@6400', '176@6000']
['18 City / 24 Hwy', '18 City / 23 Hwy', '27 City / 38 Hwy', '25 City / 32 Hwy', '26 City / 32 Hwy', '18 City / 23 Hwy', '28 City / 36 Hwy', '19 City / 23 Hwy', '26 City / 32 Hwy', '23 City / 30 Hwy']
['Truck', 'Truck', 'Sedan', 'Wagon', 'SUV/Crossover', 'Truck', 'Sedan', 'Truck', 'SUV/Crossover', 'SUV/Crossover']
['RWD', 'RWD', 'FWD', 'AWD', 'FWD', 'RWD', 'FWD', 'RWD', 'FWD', 'FWD']
['Unleaded Regular', 'Unleaded Regular', 'Unleaded Regular', 'Unleaded Regular', 'Unleaded Regular', 'Unleaded Regular', 'Unleaded Regular', 'Unleaded Regular', 'Unleaded Regular', 'Unleaded Regular']
['3/3', '3/2', '5/5', '5/5', '5/7', '3/5', '5/5', '4/2', '5/5', '5/5']
https://st.motortrend.com/uploads/sites/10/2018/05/2019-Toyota-RAV4-front-three-quarter-in-motion-05.jpg
['$26,540', '$27,815', '$18,640', '$24,995', '$23,330', '$27,095', '$17,300', '$23,660', '$23,845', '$24,350', '$23,100']
['$23,900', '$20,350', '$18,640', '$19,175', '$16,225', '$20,000', '$17,300', '$20,000', '$17,075', '$18,675', '$14,425']
['$21,610', '$18,685', 'N/A', '$17,890', '$15,115', '$18,435', 'N/A', '$18,501', '$15,876', '$17,401', '$13,140']
['Below Average', 'Excellent', 'N/A', 'Average', 'Average', 'Excellent', 'N/A', 'Excellent', 'Excellent', 'Excellent', 'Excellent']
['Engine: V6 Flex Fuel 3.5 Liter', 'Engine: V6 Flex Fuel 4.3 Liter EcoTec3', 'Engine: 4-Cyl 2.0 Liter', 'Engine: 4-Cyl 2.5 Liter BOXER', 'Engine: 4-Cyl 2.5 Liter', 'Engine: V6 Flex Fuel 4.3 Liter EcoTec3', 'Engine: 4-Cyl 1.8 Liter', 'Engine: 4-Cyl 2.7 Liter', 'Engine: 4-Cyl 2.4 Liter Earth Dreams Technology™', 'Engine: 4-Cyl 2.5 Liter', 'Engine: 4-Cyl 2.5 Liter Duratec']
['SelectShift® 6 Speed Automatic Mode Select with Manual Mode (6R80E)', 'Hydra-Matic 6 Speed Automatic Mode Select (6L80)', '6 Speed Manual', 'Lineartronic CVT Continuously Variable Automatic Mode Select with Manual Mode', 'Xtronic Continuously Variable Automatic Mode Select', 'Hydra-Matic 6 Speed Automatic Mode Select with Manual Mode (6L80)', '6 Speed Manual', 'ECT-i 6 Speed Automatic Mode Select with Manual Mode', 'Continuously Variable Automatic Mode Select', 'ECT-i 6 Speed Automatic Mode Select with Manual Mode', 'SelectShift 6 Speed Automatic with Manual Mode (L40D)']
['XL 2WD Short Bed Regular Cab', 'Base 2WD Standard Bed Regular Cab', 'LX (Manual) Sedan', '2.5i Wagon', 'S 2WD', 'Work Truck 1WT 2WD Standard Bed Regular Cab', 'L (Manual) Sedan', 'SR 2WD Access Cab', 'LX 2WD', 'LE FWD', 'S']
['Full-Size Pickup LD', 'Full-Size Pickup LD', 'Compact Passenger Car', 'Mid-Size Utility', 'Compact Utility', 'Full-Size Pickup LD', 'Compact Passenger Car', 'Mid-Size Pickup', 'Mid-Size Utility', 'Mid-Size Utility', 'Mid-Size Utility']
['283@6500', '285@5300', '158@6500', '175@5800', '170@6000', '285@5300', '132@6000', '159@5200', '185@6400', '176@6000', '168@6000']
['18 City / 24 Hwy', '18 City / 23 Hwy', '27 City / 38 Hwy', '25 City / 32 Hwy', '26 City / 32 Hwy', '18 City / 23 Hwy', '28 City / 36 Hwy', '19 City / 23 Hwy', '26 City / 32 Hwy', '23 City / 30 Hwy', '22 City / 30 Hwy']
['Truck', 'Truck', 'Sedan', 'Wagon', 'SUV/Crossover', 'Truck', 'Sedan', 'Truck', 'SUV/Crossover', 'SUV/Crossover', 'SUV/Crossover']
['RWD', 'RWD', 'FWD', 'AWD', 'FWD', 'RWD', 'FWD', 'RWD', 'FWD', 'FWD', 'FWD']
['Unleaded Regular', 'Unleaded Regular', 'Unleaded Regular', 'Unleaded Regular', 'Unleaded Regular', 'Unleaded Regular', 'Unleaded Regular', 'Unleaded Regular', 'Unleaded Regular', 'Unleaded Regular', 'Unleaded Regular']
['3/3', '3/2', '5/5', '5/5', '5/7', '3/5', '5/5', '4/2', '5/5', '5/5', '5/5']
https://st.motortrend.com/uploads/sites/10/2019/04/2020-Ford-Escape-1.jpg
['$26,540', '$27,815', '$18,640', '$24,995', '$23,330', '$27,095', '$17,300', '$23,660', '$23,845', '$24,350', '$23,100', '$22,205']
['$23,900', '$20,350', '$18,640', '$19,175', '$16,225', '$20,000', '$17,300', '$20,000', '$17,075', '$18,675', '$14,425', '$22,205']
['$21,610', '$18,685', 'N/A', '$17,890', '$15,115', '$18,435', 'N/A', '$18,501', '$15,876', '$17,401', '$13,140', 'N/A']
['Below Average', 'Excellent', 'N/A', 'Average', 'Average', 'Excellent', 'N/A', 'Excellent', 'Excellent', 'Excellent', 'Excellent', 'N/A']
['Engine: V6 Flex Fuel 3.5 Liter', 'Engine: V6 Flex Fuel 4.3 Liter EcoTec3', 'Engine: 4-Cyl 2.0 Liter', 'Engine: 4-Cyl 2.5 Liter BOXER', 'Engine: 4-Cyl 2.5 Liter', 'Engine: V6 Flex Fuel 4.3 Liter EcoTec3', 'Engine: 4-Cyl 1.8 Liter', 'Engine: 4-Cyl 2.7 Liter', 'Engine: 4-Cyl 2.4 Liter Earth Dreams Technology™', 'Engine: 4-Cyl 2.5 Liter', 'Engine: 4-Cyl 2.5 Liter Duratec', 'Engine: 4-Cyl 2.4 Liter Earth Dreams Technology™']
['SelectShift® 6 Speed Automatic Mode Select with Manual Mode (6R80E)', 'Hydra-Matic 6 Speed Automatic Mode Select (6L80)', '6 Speed Manual', 'Lineartronic CVT Continuously Variable Automatic Mode Select with Manual Mode', 'Xtronic Continuously Variable Automatic Mode Select', 'Hydra-Matic 6 Speed Automatic Mode Select with Manual Mode (6L80)', '6 Speed Manual', 'ECT-i 6 Speed Automatic Mode Select with Manual Mode', 'Continuously Variable Automatic Mode Select', 'ECT-i 6 Speed Automatic Mode Select with Manual Mode', 'SelectShift 6 Speed Automatic with Manual Mode (L40D)', '6 Speed Manual']
['XL 2WD Short Bed Regular Cab', 'Base 2WD Standard Bed Regular Cab', 'LX (Manual) Sedan', '2.5i Wagon', 'S 2WD', 'Work Truck 1WT 2WD Standard Bed Regular Cab', 'L (Manual) Sedan', 'SR 2WD Access Cab', 'LX 2WD', 'LE FWD', 'S', 'LX (Manual) Sedan']
['Full-Size Pickup LD', 'Full-Size Pickup LD', 'Compact Passenger Car', 'Mid-Size Utility', 'Compact Utility', 'Full-Size Pickup LD', 'Compact Passenger Car', 'Mid-Size Pickup', 'Mid-Size Utility', 'Mid-Size Utility', 'Mid-Size Utility', 'Passenger Car']
['283@6500', '285@5300', '158@6500', '175@5800', '170@6000', '285@5300', '132@6000', '159@5200', '185@6400', '176@6000', '168@6000', '185@6400']
['18 City / 24 Hwy', '18 City / 23 Hwy', '27 City / 38 Hwy', '25 City / 32 Hwy', '26 City / 32 Hwy', '18 City / 23 Hwy', '28 City / 36 Hwy', '19 City / 23 Hwy', '26 City / 32 Hwy', '23 City / 30 Hwy', '22 City / 30 Hwy', '23 City / 33 Hwy']
['Truck', 'Truck', 'Sedan', 'Wagon', 'SUV/Crossover', 'Truck', 'Sedan', 'Truck', 'SUV/Crossover', 'SUV/Crossover', 'SUV/Crossover', 'Sedan']
['RWD', 'RWD', 'FWD', 'AWD', 'FWD', 'RWD', 'FWD', 'RWD', 'FWD', 'FWD', 'FWD', 'FWD']
['Unleaded Regular', 'Unleaded Regular', 'Unleaded Regular', 'Unleaded Regular', 'Unleaded Regular', 'Unleaded Regular', 'Unleaded Regular', 'Unleaded Regular', 'Unleaded Regular', 'Unleaded Regular', 'Unleaded Regular', 'Unleaded Regular']
['3/3', '3/2', '5/5', '5/5', '5/7', '3/5', '5/5', '4/2', '5/5', '5/5', '5/5', '5/5']
https://st.motortrend.com/uploads/sites/10/2017/07/2018-Honda-Accord-Touring-front-three-quarter.jpg

['$26,540', '$27,815', '$18,640', '$24,995', '$23,330', '$27,095', '$17,300', '$23,660', '$23,845', '$24,350', '$23,100', '$22,205', '$14,895']
['$23,900', '$20,350', '$18,640', '$19,175', '$16,225', '$20,000', '$17,300', '$20,000', '$17,075', '$18,675', '$14,425', '$22,205', '$14,895']
['$21,610', '$18,685', 'N/A', '$17,890', '$15,115', '$18,435', 'N/A', '$18,501', '$15,876', '$17,401', '$13,140', 'N/A', 'N/A']
['Below Average', 'Excellent', 'N/A', 'Average', 'Average', 'Excellent', 'N/A', 'Excellent', 'Excellent', 'Excellent', 'Excellent', 'N/A', 'N/A']
['Engine: V6 Flex Fuel 3.5 Liter', 'Engine: V6 Flex Fuel 4.3 Liter EcoTec3', 'Engine: 4-Cyl 2.0 Liter', 'Engine: 4-Cyl 2.5 Liter BOXER', 'Engine: 4-Cyl 2.5 Liter', 'Engine: V6 Flex Fuel 4.3 Liter EcoTec3', 'Engine: 4-Cyl 1.8 Liter', 'Engine: 4-Cyl 2.7 Liter', 'Engine: 4-Cyl 2.4 Liter Earth Dreams Technology™', 'Engine: 4-Cyl 2.5 Liter', 'Engine: 4-Cyl 2.5 Liter Duratec', 'Engine: 4-Cyl 2.4 Liter Earth Dreams Technology™', 'Engine: 4-Cyl 1.5 Liter']
['SelectShift® 6 Speed Automatic Mode Select with Manual Mode (6R80E)', 'Hydra-Matic 6 Speed Automatic Mode Select (6L80)', '6 Speed Manual', 'Lineartronic CVT Continuously Variable Automatic Mode Select with Manual Mode', 'Xtronic Continuously Variable Automatic Mode Select', 'Hydra-Matic 6 Speed Automatic Mode Select with Manual Mode (6L80)', '6 Speed Manual', 'ECT-i 6 Speed Automatic Mode Select with Manual Mode', 'Continuously Variable Automatic Mode Select', 'ECT-i 6 Speed Automatic Mode Select with Manual Mode', 'SelectShift 6 Speed Automatic with Manual Mode (L40D)', '6 Speed Manual', '5 Speed Manual']
['XL 2WD Short Bed Regular Cab', 'Base 2WD Standard Bed Regular Cab', 'LX (Manual) Sedan', '2.5i Wagon', 'S 2WD', 'Work Truck 1WT 2WD Standard Bed Regular Cab', 'L (Manual) Sedan', 'SR 2WD Access Cab', 'LX 2WD', 'LE FWD', 'S', 'LX (Manual) Sedan', 'L (Manual) 2-Door Hatchback']
['Full-Size Pickup LD', 'Full-Size Pickup LD', 'Compact Passenger Car', 'Mid-Size Utility', 'Compact Utility', 'Full-Size Pickup LD', 'Compact Passenger Car', 'Mid-Size Pickup', 'Mid-Size Utility', 'Mid-Size Utility', 'Mid-Size Utility', 'Passenger Car', 'Sporty/Coupe']
['283@6500', '285@5300', '158@6500', '175@5800', '170@6000', '285@5300', '132@6000', '159@5200', '185@6400', '176@6000', '168@6000', '185@6400', '106@6000']
['18 City / 24 Hwy', '18 City / 23 Hwy', '27 City / 38 Hwy', '25 City / 32 Hwy', '26 City / 32 Hwy', '18 City / 23 Hwy', '28 City / 36 Hwy', '19 City / 23 Hwy', '26 City / 32 Hwy', '23 City / 30 Hwy', '22 City / 30 Hwy', '23 City / 33 Hwy', '30 City / 36 Hwy']
['Truck', 'Truck', 'Sedan', 'Wagon', 'SUV/Crossover', 'Truck', 'Sedan', 'Truck', 'SUV/Crossover', 'SUV/Crossover', 'SUV/Crossover', 'Sedan', 'Hatchback']
['RWD', 'RWD', 'FWD', 'AWD', 'FWD', 'RWD', 'FWD', 'RWD', 'FWD', 'FWD', 'FWD', 'FWD', 'FWD']
['Unleaded Regular', 'Unleaded Regular', 'Unleaded Regular', 'Unleaded Regular', 'Unleaded Regular', 'Unleaded Regular', 'Unleaded Regular', 'Unleaded Regular', 'Unleaded Regular', 'Unleaded Regular', 'Unleaded Regular', 'Unleaded Regular', 'Unleaded Regular']
['3/3', '3/2', '5/5', '5/5', '5/7', '3/5', '5/5', '4/2', '5/5', '5/5', '5/5', '5/5', '5/5']
https://st.motortrend.com/uploads/sites/10/2018/06/2018-toyota-yaris-l-3door-hatchback-angular-front.png

In [18]:
df_prelim = pd.DataFrame({
    'Model': unique_cars_df['Model'],
    'Manufacturer_Suggested_Retail_Price':MSRP,
    'Certified_Pre-Owned_Price':CPO,
    'Used_Car_Value':UCV,
    'Value_Rating':VR,
    'Engine_Name':EN,
    'Transmission_Name':TN,
    'Trim':T,
    'Class':C,
    'Horsepower':HP,
    'Standard_MPG':MPG,
    'Body_Style':BSt,
    'Drivetrain':DT,
    'Fuel_Type':FT,
    'Seating_Capacity':SC,
    'Image_URL':IMGURL
})

df_prelim.head()

,Model,Manufacturer_Suggested_Retail_Price,Certified_Pre-Owned_Price,Used_Car_Value,Value_Rating,Engine_Name,Transmission_Name,Trim,Class,Horsepower,Standard_MPG,Body_Style,Drivetrain,Fuel_Type,Seating_Capacity,Image_URL
0,F-150,"$26,540","$23,900","$21,610",Below Average,Engine: V6 Flex Fuel 3.5 Liter,SelectShift® 6 Speed Automatic Mode Select wit...,XL 2WD Short Bed Regular Cab,Full-Size Pickup LD,283@6500,18 City / 24 Hwy,Truck,RWD,Unleaded Regular,3/3,https://st.motortrend.com/uploads/sites/10/201...
1,Sierra-1500,"$27,815","$20,350","$18,685",Excellent,Engine: V6 Flex Fuel 4.3 Liter EcoTec3,Hydra-Matic 6 Speed Automatic Mode Select (6L80),Base 2WD Standard Bed Regular Cab,Full-Size Pickup LD,285@5300,18 City / 23 Hwy,Truck,RWD,Unleaded Regular,3/2,https://st.motortrend.com/uploads/sites/10/201...
2,Civic,"$18,640","$18,640",N/A,N/A,Engine: 4-Cyl 2.0 Liter,6 Speed Manual,LX (Manual) Sedan,Compact Passenger Car,158@6500,27 City / 38 Hwy,Sedan,FWD,Unleaded Regular,5/5,https://st.motortrend.com/uploads/sites/10/201...
3,Outback,"$24,995","$19,175","$17,890",Average,Engine: 4-Cyl 2.5 Liter BOXER,Lineartronic CVT Continuously Variable Automat...,2.5i Wagon,Mid-Size Utility,175@5800,25 City / 32 Hwy,Wagon,AWD,Unleaded Regular,5/5,https://st.motortrend.com/uploads/sites/10/201...
4,Rogue,"$23,330","$16,225","$15,115",Average,Engine: 4-Cyl 2.5 Liter,Xtronic Continuously Variable Automatic Mode S...,S 2WD,Compact Utility,170@6000,26 City / 32 Hwy,SUV/Crossover,FWD,Unleaded Regular,5/7,https://st.motortrend.com/uploads/sites/10/201...

In [19]:
df.head()

        State        Model   Make
0      Alaska        F-150   Ford
1     Alabama        F-150   Ford
2     Arizona        F-150   Ford
3    Arkansas  Sierra-1500    GMC
4  California        Civic  Honda

In [20]:
final_df = df.merge(df_prelim, how = 'left', on = 'Model')

final_df.head()

,State,Model,Make,Manufacturer_Suggested_Retail_Price,Certified_Pre-Owned_Price,Used_Car_Value,Value_Rating,Engine_Name,Transmission_Name,Trim,Class,Horsepower,Standard_MPG,Body_Style,Drivetrain,Fuel_Type,Seating_Capacity,Image_URL
0,Alaska,F-150,Ford,"$26,540","$23,900","$21,610",Below Average,Engine: V6 Flex Fuel 3.5 Liter,SelectShift® 6 Speed Automatic Mode Select wit...,XL 2WD Short Bed Regular Cab,Full-Size Pickup LD,283@6500,18 City / 24 Hwy,Truck,RWD,Unleaded Regular,3/3,https://st.motortrend.com/uploads/sites/10/201...
1,Alabama,F-150,Ford,"$26,540","$23,900","$21,610",Below Average,Engine: V6 Flex Fuel 3.5 Liter,SelectShift® 6 Speed Automatic Mode Select wit...,XL 2WD Short Bed Regular Cab,Full-Size Pickup LD,283@6500,18 City / 24 Hwy,Truck,RWD,Unleaded Regular,3/3,https://st.motortrend.com/uploads/sites/10/201...
2,Arizona,F-150,Ford,"$26,540","$23,900","$21,610",Below Average,Engine: V6 Flex Fuel 3.5 Liter,SelectShift® 6 Speed Automatic Mode Select wit...,XL 2WD Short Bed Regular Cab,Full-Size Pickup LD,283@6500,18 City / 24 Hwy,Truck,RWD,Unleaded Regular,3/3,https://st.motortrend.com/uploads/sites/10/201...
3,Arkansas,Sierra-1500,GMC,"$27,815","$20,350","$18,685",Excellent,Engine: V6 Flex Fuel 4.3 Liter EcoTec3,Hydra-Matic 6 Speed Automatic Mode Select (6L80),Base 2WD Standard Bed Regular Cab,Full-Size Pickup LD,285@5300,18 City / 23 Hwy,Truck,RWD,Unleaded Regular,3/2,https://st.motortrend.com/uploads/sites/10/201...
4,California,Civic,Honda,"$18,640","$18,640",N/A,N/A,Engine: 4-Cyl 2.0 Liter,6 Speed Manual,LX (Manual) Sedan,Compact Passenger Car,158@6500,27 City / 38 Hwy,Sedan,FWD,Unleaded Regular,5/5,https://st.motortrend.com/uploads/sites/10/201...

# Update JSON File

In [27]:
with open('state_boundaries.json', 'r') as f:
    datastore = json.load(f)

In [28]:
panel_df =  final_df[['State', 'Model', 'Make', 'Manufacturer_Suggested_Retail_Price', 'Class', 'Standard_MPG', \
                      'Body_Style', 'Image_URL']]
car_info_dict = panel_df.to_dict(orient='records')

car_info_dict

[{'State': 'Alaska',
  'Model': 'F-150',
  'Make': 'Ford',
  'Manufacturer_Suggested_Retail_Price': '$26,540',
  'Class': 'Full-Size Pickup LD',
  'Standard_MPG': '18 City / 24 Hwy',
  'Body_Style': 'Truck',
  'Image_URL': 'https://st.motortrend.com/uploads/sites/10/2017/11/2018-ford-f-150-xlt-supercab-pick-up-angular-front.png'},
 {'State': 'Alabama',
  'Model': 'F-150',
  'Make': 'Ford',
  'Manufacturer_Suggested_Retail_Price': '$26,540',
  'Class': 'Full-Size Pickup LD',
  'Standard_MPG': '18 City / 24 Hwy',
  'Body_Style': 'Truck',
  'Image_URL': 'https://st.motortrend.com/uploads/sites/10/2017/11/2018-ford-f-150-xlt-supercab-pick-up-angular-front.png'},
 {'State': 'Arizona',
  'Model': 'F-150',
  'Make': 'Ford',
  'Manufacturer_Suggested_Retail_Price': '$26,540',
  'Class': 'Full-Size Pickup LD',
  'Standard_MPG': '18 City / 24 Hwy',
  'Body_Style': 'Truck',
  'Image_URL': 'https://st.motortrend.com/uploads/sites/10/2017/11/2018-ford-f-150-xlt-supercab-pick-up-angular-front.png'},
 {'State': 'Arkansas',
  'Model': 'Sierra-1500',
  'Make': 'GMC',
  'Manufacturer_Suggested_Retail_Price': '$27,815',
  'Class': 'Full-Size Pickup LD',
  'Standard_MPG': '18 City / 23 Hwy',
  'Body_Style': 'Truck',
  'Image_URL': 'https://st.motortrend.com/uploads/sites/10/2018/03/2019-GMC-Sierra-1500-Denali-front-view.jpg'},
 {'State': 'California',
  'Model': 'Civic',
  'Make': 'Honda',
  'Manufacturer_Suggested_Retail_Price': '$18,640',
  'Class': 'Compact Passenger Car',
  'Standard_MPG': '27 City / 38 Hwy',
  'Body_Style': 'Sedan',
  'Image_URL': 'https://st.motortrend.com/uploads/sites/10/2018/08/2019-Honda-Civic-Coupe-Sport.jpg'},
 {'State': 'Colorado',
  'Model': 'Outback',
  'Make': 'Subaru',
  'Manufacturer_Suggested_Retail_Price': '$24,995',
  'Class': 'Mid-Size Utility',
  'Standard_MPG': '25 City / 32 Hwy',
  'Body_Style': 'Wagon',
  'Image_URL': 'https://st.motortrend.com/uploads/sites/10/2017/10/2018-subaru-outback-premium-wagon-angular-front.png'},
 {'State': 'Connecticut',
  'Model': 'Rogue',
  'Make': 'Nissan',
  'Manufacturer_Suggested_Retail_Price': '$23,330',
  'Class': 'Compact Utility',
  'Standard_MPG': '26 City / 32 Hwy',
  'Body_Style': 'SUV/Crossover',
  'Image_URL': 'https://st.motortrend.com/uploads/sites/10/2017/12/2018-nissan-rogue-s-suv-angular-front.png'},
 {'State': 'Washington, D.C.',
  'Model': 'Civic',
  'Make': 'Honda',
  'Manufacturer_Suggested_Retail_Price': '$18,640',
  'Class': 'Compact Passenger Car',
  'Standard_MPG': '27 City / 38 Hwy',
  'Body_Style': 'Sedan',
  'Image_URL': 'https://st.motortrend.com/uploads/sites/10/2018/08/2019-Honda-Civic-Coupe-Sport.jpg'},
 {'State': 'Delaware',
  'Model': 'Silverado-1500',
  'Make': 'Chevrolet',
  'Manufacturer_Suggested_Retail_Price': '$27,095',
  'Class': 'Full-Size Pickup LD',
  'Standard_MPG': '18 City / 23 Hwy',
  'Body_Style': 'Truck',
  'Image_URL': 'https://st.motortrend.com/uploads/sites/10/2018/01/2019-Chevrolet-Silverado-1500-front-side-view-1.jpg'},
 {'State': 'Florida',
  'Model': 'Corolla',
  'Make': 'Toyota',
  'Manufacturer_Suggested_Retail_Price': '$17,300',
  'Class': 'Compact Passenger Car',
  'Standard_MPG': '28 City / 36 Hwy',
  'Body_Style': 'Sedan',
  'Image_URL': 'https://st.motortrend.com/uploads/sites/10/2017/10/2018-toyota-corolla-l-sedan-angular-front.png'},
 {'State': 'Georgia',
  'Model': 'F-150',
  'Make': 'Ford',
  'Manufacturer_Suggested_Retail_Price': '$26,540',
  'Class': 'Full-Size Pickup LD',
  'Standard_MPG': '18 City / 24 Hwy',
  'Body_Style': 'Truck',
  'Image_URL': 'https://st.motortrend.com/uploads/sites/10/2017/11/2018-ford-f-150-xlt-supercab-pick-up-angular-front.png'},
 {'State': 'Hawaii',
  'Model': 'Tacoma',
  'Make': 'Toyota',
  'Manufacturer_Suggested_Retail_Price': '$23,660',
  'Class': 'Mid-Size Pickup',
  'Standard_MPG': '19 City / 23 Hwy',
  'Body_Style': 'Truck',
  'Image_URL': 'https://st.motortrend.com/uploads/sites/10/2019/02/2020-Toyota-Tacoma-TRD-Off-Road-1.jpg'},
 {'State': 'Iowa',
  'Model': 'Silverado-1500',
  'Make': 'Chevrolet',
  'Manufacturer_Suggested_Retail_Price': '$27,095',
  'Class': 'Full-Size Pickup LD',
  'Standard_MPG': '18 City / 23 Hwy',
  'Body_Style': 'Truck',
  'Image_URL': 'https://st.motortrend.com/uploads/sites/10/2018/01/2019-Chevrolet-Silverado-1500-front-side-view-1.jpg'},
 {'State': 'Idaho',
  'Model': 'F-150',
  'Make': 'Ford',
  'Manufacturer_Suggested_Retail_Price': '$26,540',
  'Class': 'Full-Size Pickup LD',
  'Standard_MPG': '18 City / 24 Hwy',
  'Body_Style': 'Truck',
  'Image_URL': 'https://st.motortrend.com/uploads/sites/10/2017/11/2018-ford-f-150-xlt-supercab-pick-up-angular-front.png'},
 {'State': 'Illinois',
  'Model': 'CR-V',
  'Make': 'Honda',
  'Manufacturer_Suggested_Retail_Price': '$23,845',
  'Class': 'Mid-Size Utility',
  'Standard_MPG': '26 City / 32 Hwy',
  'Body_Style': 'SUV/Crossover',
  'Image_URL': 'https://st.motortrend.com/uploads/sites/10/2017/10/2018-Honda-CR-V-front-three-quarter-in-motion-01.jpg'},
 {'State': 'Indiana',
  'Model': 'Silverado-1500',
  'Make': 'Chevrolet',
  'Manufacturer_Suggested_Retail_Price': '$27,095',
  'Class': 'Full-Size Pickup LD',
  'Standard_MPG': '18 City / 23 Hwy',
  'Body_Style': 'Truck',
  'Image_URL': 'https://st.motortrend.com/uploads/sites/10/2018/01/2019-Chevrolet-Silverado-1500-front-side-view-1.jpg'},
 {'State': 'Kansas',
  'Model': 'F-150',
  'Make': 'Ford',
  'Manufacturer_Suggested_Retail_Price': '$26,540',
  'Class': 'Full-Size Pickup LD',
  'Standard_MPG': '18 City / 24 Hwy',
  'Body_Style': 'Truck',
  'Image_URL': 'https://st.motortrend.com/uploads/sites/10/2017/11/2018-ford-f-150-xlt-supercab-pick-up-angular-front.png'},
 {'State': 'Kentucky',
  'Model': 'F-150',
  'Make': 'Ford',
  'Manufacturer_Suggested_Retail_Price': '$26,540',
  'Class': 'Full-Size Pickup LD',
  'Standard_MPG': '18 City / 24 Hwy',
  'Body_Style': 'Truck',
  'Image_URL': 'https://st.motortrend.com/uploads/sites/10/2017/11/2018-ford-f-150-xlt-supercab-pick-up-angular-front.png'},
 {'State': 'Louisiana',
  'Model': 'F-150',
  'Make': 'Ford',
  'Manufacturer_Suggested_Retail_Price': '$26,540',
  'Class': 'Full-Size Pickup LD',
  'Standard_MPG': '18 City / 24 Hwy',
  'Body_Style': 'Truck',
  'Image_URL': 'https://st.motortrend.com/uploads/sites/10/2017/11/2018-ford-f-150-xlt-supercab-pick-up-angular-front.png'},
 {'State': 'Massachusetts',
  'Model': 'RAV4',
  'Make': 'Toyota',
  'Manufacturer_Suggested_Retail_Price': '$24,350',
  'Class': 'Mid-Size Utility',
  'Standard_MPG': '23 City / 30 Hwy',
  'Body_Style': 'SUV/Crossover',
  'Image_URL': 'https://st.motortrend.com/uploads/sites/10/2018/05/2019-Toyota-RAV4-front-three-quarter-in-motion-05.jpg'},
 {'State': 'Maryland',
  'Model': 'CR-V',
  'Make': 'Honda',
  'Manufacturer_Suggested_Retail_Price': '$23,845',
  'Class': 'Mid-Size Utility',
  'Standard_MPG': '26 City / 32 Hwy',
  'Body_Style': 'SUV/Crossover',
  'Image_URL': 'https://st.motortrend.com/uploads/sites/10/2017/10/2018-Honda-CR-V-front-three-quarter-in-motion-01.jpg'},
 {'State': 'Maine',
  'Model': 'Silverado-1500',
  'Make': 'Chevrolet',
  'Manufacturer_Suggested_Retail_Price': '$27,095',
  'Class': 'Full-Size Pickup LD',
  'Standard_MPG': '18 City / 23 Hwy',
  'Body_Style': 'Truck',
  'Image_URL': 'https://st.motortrend.com/uploads/sites/10/2018/01/2019-Chevrolet-Silverado-1500-front-side-view-1.jpg'},
 {'State': 'Michigan',
  'Model': 'Escape',
  'Make': 'Ford',
  'Manufacturer_Suggested_Retail_Price': '$23,100',
  'Class': 'Mid-Size Utility',
  'Standard_MPG': '22 City / 30 Hwy',
  'Body_Style': 'SUV/Crossover',
  'Image_URL': 'https://st.motortrend.com/uploads/sites/10/2019/04/2020-Ford-Escape-1.jpg'},
 {'State': 'Minnesota',
  'Model': 'F-150',
  'Make': 'Ford',
  'Manufacturer_Suggested_Retail_Price': '$26,540',
  'Class': 'Full-Size Pickup LD',
  'Standard_MPG': '18 City / 24 Hwy',
  'Body_Style': 'Truck',
  'Image_URL': 'https://st.motortrend.com/uploads/sites/10/2017/11/2018-ford-f-150-xlt-supercab-pick-up-angular-front.png'},
 {'State': 'Missouri',
  'Model': 'F-150',
  'Make': 'Ford',
  'Manufacturer_Suggested_Retail_Price': '$26,540',
  'Class': 'Full-Size Pickup LD',
  'Standard_MPG': '18 City / 24 Hwy',
  'Body_Style': 'Truck',
  'Image_URL': 'https://st.motortrend.com/uploads/sites/10/2017/11/2018-ford-f-150-xlt-supercab-pick-up-angular-front.png'},
 {'State': 'Mississippi',
  'Model': 'F-150',
  'Make': 'Ford',
  'Manufacturer_Suggested_Retail_Price': '$26,540',
  'Class': 'Full-Size Pickup LD',
  'Standard_MPG': '18 City / 24 Hwy',
  'Body_Style': 'Truck',
  'Image_URL': 'https://st.motortrend.com/uploads/sites/10/2017/11/2018-ford-f-150-xlt-supercab-pick-up-angular-front.png'},
 {'State': 'Montana',
  'Model': 'F-150',
  'Make': 'Ford',
  'Manufacturer_Suggested_Retail_Price': '$26,540',
  'Class': 'Full-Size Pickup LD',
  'Standard_MPG': '18 City / 24 Hwy',
  'Body_Style': 'Truck',
  'Image_URL': 'https://st.motortrend.com/uploads/sites/10/2017/11/2018-ford-f-150-xlt-supercab-pick-up-angular-front.png'},
 {'State': 'North Carolina',
  'Model': 'Accord',
  'Make': 'Honda',
  'Manufacturer_Suggested_Retail_Price': '$22,205',
  'Class': 'Passenger Car',
  'Standard_MPG': '23 City / 33 Hwy',
  'Body_Style': 'Sedan',
  'Image_URL': 'https://st.motortrend.com/uploads/sites/10/2017/07/2018-Honda-Accord-Touring-front-three-quarter.jpg'},
 {'State': 'North Dakota',
  'Model': 'F-150',
  'Make': 'Ford',
  'Manufacturer_Suggested_Retail_Price': '$26,540',
  'Class': 'Full-Size Pickup LD',
  'Standard_MPG': '18 City / 24 Hwy',
  'Body_Style': 'Truck',
  'Image_URL': 'https://st.motortrend.com/uploads/sites/10/2017/11/2018-ford-f-150-xlt-supercab-pick-up-angular-front.png'},
 {'State': 'Nebraska',
  'Model': 'F-150',
  'Make': 'Ford',
  'Manufacturer_Suggested_Retail_Price': '$26,540',
  'Class': 'Full-Size Pickup LD',
  'Standard_MPG': '18 City / 24 Hwy',
  'Body_Style': 'Truck',
  'Image_URL': 'https://st.motortrend.com/uploads/sites/10/2017/11/2018-ford-f-150-xlt-supercab-pick-up-angular-front.png'},
 {'State': 'New Hampshire',
  'Model': 'Silverado-1500',
  'Make': 'Chevrolet',
  'Manufacturer_Suggested_Retail_Price': '$27,095',
  'Class': 'Full-Size Pickup LD',
  'Standard_MPG': '18 City / 23 Hwy',
  'Body_Style': 'Truck',
  'Image_URL': 'https://st.motortrend.com/uploads/sites/10/2018/01/2019-Chevrolet-Silverado-1500-front-side-view-1.jpg'},
 {'State': 'New Jersey',
  'Model': 'CR-V',
  'Make': 'Honda',
  'Manufacturer_Suggested_Retail_Price': '$23,845',
  'Class': 'Mid-Size Utility',
  'Standard_MPG': '26 City / 32 Hwy',
  'Body_Style': 'SUV/Crossover',
  'Image_URL': 'https://st.motortrend.com/uploads/sites/10/2017/10/2018-Honda-CR-V-front-three-quarter-in-motion-01.jpg'},
 {'State': 'New Mexico',
  'Model': 'F-150',
  'Make': 'Ford',
  'Manufacturer_Suggested_Retail_Price': '$26,540',
  'Class': 'Full-Size Pickup LD',
  'Standard_MPG': '18 City / 24 Hwy',
  'Body_Style': 'Truck',
  'Image_URL': 'https://st.motortrend.com/uploads/sites/10/2017/11/2018-ford-f-150-xlt-supercab-pick-up-angular-front.png'},
 {'State': 'Nevada',
  'Model': 'RAV4',
  'Make': 'Toyota',
  'Manufacturer_Suggested_Retail_Price': '$24,350',
  'Class': 'Mid-Size Utility',
  'Standard_MPG': '23 City / 30 Hwy',
  'Body_Style': 'SUV/Crossover',
  'Image_URL': 'https://st.motortrend.com/uploads/sites/10/2018/05/2019-Toyota-RAV4-front-three-quarter-in-motion-05.jpg'},
 {'State': 'New York',
  'Model': 'Rogue',
  'Make': 'Nissan',
  'Manufacturer_Suggested_Retail_Price': '$23,330',
  'Class': 'Compact Utility',
  'Standard_MPG': '26 City / 32 Hwy',
  'Body_Style': 'SUV/Crossover',
  'Image_URL': 'https://st.motortrend.com/uploads/sites/10/2017/12/2018-nissan-rogue-s-suv-angular-front.png'},
 {'State': 'Ohio',
  'Model': 'Civic',
  'Make': 'Honda',
  'Manufacturer_Suggested_Retail_Price': '$18,640',
  'Class': 'Compact Passenger Car',
  'Standard_MPG': '27 City / 38 Hwy',
  'Body_Style': 'Sedan',
  'Image_URL': 'https://st.motortrend.com/uploads/sites/10/2018/08/2019-Honda-Civic-Coupe-Sport.jpg'},
 {'State': 'Oklahoma',
  'Model': 'F-150',
  'Make': 'Ford',
  'Manufacturer_Suggested_Retail_Price': '$26,540',
  'Class': 'Full-Size Pickup LD',
  'Standard_MPG': '18 City / 24 Hwy',
  'Body_Style': 'Truck',
  'Image_URL': 'https://st.motortrend.com/uploads/sites/10/2017/11/2018-ford-f-150-xlt-supercab-pick-up-angular-front.png'},
 {'State': 'Oregon',
  'Model': 'Outback',
  'Make': 'Subaru',
  'Manufacturer_Suggested_Retail_Price': '$24,995',
  'Class': 'Mid-Size Utility',
  'Standard_MPG': '25 City / 32 Hwy',
  'Body_Style': 'Wagon',
  'Image_URL': 'https://st.motortrend.com/uploads/sites/10/2017/10/2018-subaru-outback-premium-wagon-angular-front.png'},
 {'State': 'Pennsylvania',
  'Model': 'CR-V',
  'Make': 'Honda',
  'Manufacturer_Suggested_Retail_Price': '$23,845',
  'Class': 'Mid-Size Utility',
  'Standard_MPG': '26 City / 32 Hwy',
  'Body_Style': 'SUV/Crossover',
  'Image_URL': 'https://st.motortrend.com/uploads/sites/10/2017/10/2018-Honda-CR-V-front-three-quarter-in-motion-01.jpg'},
 {'State': 'Puerto Rico',
  'Model': 'Yaris',
  'Make': 'Toyota',
  'Manufacturer_Suggested_Retail_Price': '$14,895',
  'Class': 'Sporty/Coupe',
  'Standard_MPG': '30 City / 36 Hwy',
  'Body_Style': 'Hatchback',
  'Image_URL': 'https://st.motortrend.com/uploads/sites/10/2018/06/2018-toyota-yaris-l-3door-hatchback-angular-front.png'},
 {'State': 'Rhode Island',
  'Model': 'RAV4',
  'Make': 'Toyota',
  'Manufacturer_Suggested_Retail_Price': '$24,350',
  'Class': 'Mid-Size Utility',
  'Standard_MPG': '23 City / 30 Hwy',
  'Body_Style': 'SUV/Crossover',
  'Image_URL': 'https://st.motortrend.com/uploads/sites/10/2018/05/2019-Toyota-RAV4-front-three-quarter-in-motion-05.jpg'},
 {'State': 'South Carolina',
  'Model': 'F-150',
  'Make': 'Ford',
  'Manufacturer_Suggested_Retail_Price': '$26,540',
  'Class': 'Full-Size Pickup LD',
  'Standard_MPG': '18 City / 24 Hwy',
  'Body_Style': 'Truck',
  'Image_URL': 'https://st.motortrend.com/uploads/sites/10/2017/11/2018-ford-f-150-xlt-supercab-pick-up-angular-front.png'},
 {'State': 'South Dakota',
  'Model': 'F-150',
  'Make': 'Ford',
  'Manufacturer_Suggested_Retail_Price': '$26,540',
  'Class': 'Full-Size Pickup LD',
  'Standard_MPG': '18 City / 24 Hwy',
  'Body_Style': 'Truck',
  'Image_URL': 'https://st.motortrend.com/uploads/sites/10/2017/11/2018-ford-f-150-xlt-supercab-pick-up-angular-front.png'},
 {'State': 'Tennessee',
  'Model': 'F-150',
  'Make': 'Ford',
  'Manufacturer_Suggested_Retail_Price': '$26,540',
  'Class': 'Full-Size Pickup LD',
  'Standard_MPG': '18 City / 24 Hwy',
  'Body_Style': 'Truck',
  'Image_URL': 'https://st.motortrend.com/uploads/sites/10/2017/11/2018-ford-f-150-xlt-supercab-pick-up-angular-front.png'},
 {'State': 'Texas',
  'Model': 'F-150',
  'Make': 'Ford',
  'Manufacturer_Suggested_Retail_Price': '$26,540',
  'Class': 'Full-Size Pickup LD',
  'Standard_MPG': '18 City / 24 Hwy',
  'Body_Style': 'Truck',
  'Image_URL': 'https://st.motortrend.com/uploads/sites/10/2017/11/2018-ford-f-150-xlt-supercab-pick-up-angular-front.png'},
 {'State': 'Utah',
  'Model': 'F-150',
  'Make': 'Ford',
  'Manufacturer_Suggested_Retail_Price': '$26,540',
  'Class': 'Full-Size Pickup LD',
  'Standard_MPG': '18 City / 24 Hwy',
  'Body_Style': 'Truck',
  'Image_URL': 'https://st.motortrend.com/uploads/sites/10/2017/11/2018-ford-f-150-xlt-supercab-pick-up-angular-front.png'},
 {'State': 'Virginia',
  'Model': 'CR-V',
  'Make': 'Honda',
  'Manufacturer_Suggested_Retail_Price': '$23,845',
  'Class': 'Mid-Size Utility',
  'Standard_MPG': '26 City / 32 Hwy',
  'Body_Style': 'SUV/Crossover',
  'Image_URL': 'https://st.motortrend.com/uploads/sites/10/2017/10/2018-Honda-CR-V-front-three-quarter-in-motion-01.jpg'},
 {'State': 'Vermont',
  'Model': 'RAV4',
  'Make': 'Toyota',
  'Manufacturer_Suggested_Retail_Price': '$24,350',
  'Class': 'Mid-Size Utility',
  'Standard_MPG': '23 City / 30 Hwy',
  'Body_Style': 'SUV/Crossover',
  'Image_URL': 'https://st.motortrend.com/uploads/sites/10/2018/05/2019-Toyota-RAV4-front-three-quarter-in-motion-05.jpg'},
 {'State': 'Washington',
  'Model': 'Outback',
  'Make': 'Subaru',
  'Manufacturer_Suggested_Retail_Price': '$24,995',
  'Class': 'Mid-Size Utility',
  'Standard_MPG': '25 City / 32 Hwy',
  'Body_Style': 'Wagon',
  'Image_URL': 'https://st.motortrend.com/uploads/sites/10/2017/10/2018-subaru-outback-premium-wagon-angular-front.png'},
 {'State': 'Wisconsin',
  'Model': 'Silverado-1500',
  'Make': 'Chevrolet',
  'Manufacturer_Suggested_Retail_Price': '$27,095',
  'Class': 'Full-Size Pickup LD',
  'Standard_MPG': '18 City / 23 Hwy',
  'Body_Style': 'Truck',
  'Image_URL': 'https://st.motortrend.com/uploads/sites/10/2018/01/2019-Chevrolet-Silverado-1500-front-side-view-1.jpg'},
 {'State': 'West Virginia',
  'Model': 'Silverado-1500',
  'Make': 'Chevrolet',
  'Manufacturer_Suggested_Retail_Price': '$27,095',
  'Class': 'Full-Size Pickup LD',
  'Standard_MPG': '18 City / 23 Hwy',
  'Body_Style': 'Truck',
  'Image_URL': 'https://st.motortrend.com/uploads/sites/10/2018/01/2019-Chevrolet-Silverado-1500-front-side-view-1.jpg'},
 {'State': 'Wyoming',
  'Model': 'F-150',
  'Make': 'Ford',
  'Manufacturer_Suggested_Retail_Price': '$26,540',
  'Class': 'Full-Size Pickup LD',
  'Standard_MPG': '18 City / 24 Hwy',
  'Body_Style': 'Truck',
  'Image_URL': 'https://st.motortrend.com/uploads/sites/10/2017/11/2018-ford-f-150-xlt-supercab-pick-up-angular-front.png'}]

In [29]:
for feature in datastore['features']:
#     print(feature['properties']['NAME'])
    for entry in car_info_dict:
        if entry['State'] == feature['properties']['NAME']:
            feature['properties']['vehicle'] = entry
            
datastore['features'][0]

{'type': 'Feature',
 'properties': {'GEO_ID': '0400000US23',
  'STATE': '23',
  'NAME': 'Maine',
  'LSAD': '',
  'CENSUSAREA': 30842.923,
  'vehicle': {'State': 'Maine',
   'Model': 'Silverado-1500',
   'Make': 'Chevrolet',
   'Manufacturer_Suggested_Retail_Price': '$27,095',
   'Class': 'Full-Size Pickup LD',
   'Standard_MPG': '18 City / 23 Hwy',
   'Body_Style': 'Truck',
   'Image_URL': 'https://st.motortrend.com/uploads/sites/10/2018/01/2019-Chevrolet-Silverado-1500-front-side-view-1.jpg'}},
 'geometry': {'type': 'MultiPolygon',
  'coordinates': [[[[-67.619761, 44.519754],
     [-67.61541, 44.521973],
     [-67.587738, 44.516196],
     [-67.582113, 44.513459],
     [-67.589259, 44.50084],
     [-67.590627, 44.49415],
     [-67.580288, 44.488068],
     [-67.562651, 44.472104],
     [-67.569189, 44.455531],
     [-67.571774, 44.453403],
     [-67.574206, 44.45173],
     [-67.588346, 44.449754],
     [-67.592755, 44.458572],
     [-67.604919, 44.502056],
     [-67.607199, 44.503576],
     [-67.614954, 44.503576],
     [-67.619211, 44.506009],
     [-67.619761, 44.519754]]],
   [[[-68.498637, 44.369686],
     [-68.478785, 44.319563],
     [-68.489641, 44.313705],
     [-68.515173, 44.324797],
     [-68.523857, 44.322397],
     [-68.533481, 44.329958],
     [-68.530394, 44.333583],
     [-68.528635, 44.344605],
     [-68.520671, 44.358357],
     [-68.52193, 44.367591],
     [-68.518573, 44.381022],
     [-68.512697, 44.384799],
     [-68.50766, 44.385219],
     [-68.501364, 44.382281],
     [-68.498637, 44.369686]]],
   [[[-68.23638, 44.266254],
     [-68.214641, 44.263156],
     [-68.211329, 44.257074],
     [-68.212474, 44.255405],
     [-68.221383, 44.257254],
     [-68.231469, 44.256016],
     [-68.23713, 44.25343],
     [-68.24031, 44.251622],
     [-68.241545, 44.247543],
     [-68.240806, 44.239723],
     [-68.248913, 44.235443],
     [-68.266669, 44.234033],
     [-68.274427, 44.237099],
     [-68.276857, 44.240794],
     [-68.274719, 44.258675],
     [-68.262128, 44.260774],
     [-68.254153, 44.257836],
     [-68.246598, 44.257836],
     [-68.241142, 44.260354],
     [-68.23638, 44.266254]]],
   [[[-68.942826, 44.281073],
     [-68.919301, 44.309872],
     [-68.919325, 44.335392],
     [-68.911634, 44.365027],
     [-68.90353, 44.378613],
     [-68.87894, 44.386584],
     [-68.868444, 44.38144],
     [-68.860649, 44.364425],
     [-68.864338, 44.355002],
     [-68.87169, 44.344662],
     [-68.883065, 44.338193],
     [-68.888706, 44.338196],
     [-68.89285, 44.334653],
     [-68.896587, 44.321986],
     [-68.88746, 44.303094],
     [-68.899445, 44.283775],
     [-68.904255, 44.279889],
     [-68.916872, 44.242866],
     [-68.92648, 44.233035],
     [-68.945976, 44.220824],
     [-68.95189, 44.218719],
     [-68.94709, 44.226792],
     [-68.955332, 44.243873],
     [-68.959468, 44.247439],
     [-68.965896, 44.249754],
     [-68.967074, 44.251968],
     [-68.965264, 44.259332],
     [-68.953686, 44.272346],
     [-68.942826, 44.281073]]],
   [[[-68.792139, 44.237819],
     [-68.769833, 44.222787],
     [-68.769047, 44.213351],
     [-68.780055, 44.203129],
     [-68.789884, 44.203915],
     [-68.801285, 44.208633],
     [-68.809149, 44.212565],
     [-68.815439, 44.214137],
     [-68.822909, 44.216496],
     [-68.829593, 44.21689],
     [-68.837849, 44.227112],
     [-68.839422, 44.236547],
     [-68.833524, 44.240872],
     [-68.827627, 44.242838],
     [-68.825631, 44.242556],
     [-68.792139, 44.237819]]],
   [[[-68.472831, 44.219767],
     [-68.460205, 44.212498],
     [-68.453843, 44.201683],
     [-68.454224, 44.199534],
     [-68.459182, 44.197681],
     [-68.48452, 44.202886],
     [-68.487227, 44.209517],
     [-68.482726, 44.227058],
     [-68.480565, 44.228591],
     [-68.470323, 44.22832],
     [-68.468572, 44.223999],
     [-68.472831, 44.219767]]],
   [[[-68.355279, 44.199096],
     [-68.333227, 44.207308],
     [-68.32423, 44.205732],
     [-68.31606, 44.200244],
     [-68.314789, 44.197157],
     [-68.318476, 44.196608],
     [-68.321178, 44.199032],
     [-68.332639, 44.192131],
     [-68.339029, 44.171839],
     [-68.347416, 44.169459],
     [-68.378872, 44.184222],
     [-68.371235, 44.193003],
     [-68.364469, 44.197534],
     [-68.355279, 44.199096]]],
   [[[-68.680773, 44.279242],
     [-68.675416, 44.279753],
     [-68.668213, 44.276511],
     [-68.658849, 44.268588],
     [-68.623554, 44.255622],
     [-68.611669, 44.244818],
     [-68.605906, 44.230772],
     [-68.580931, 44.213432],
     [-68.564275, 44.199155],
     [-68.563085, 44.193207],
     [-68.567249, 44.187258],
     [-68.577957, 44.185473],
     [-68.599372, 44.193207],
     [-68.612749, 44.207722],
     [-68.624994, 44.197637],
     [-68.625715, 44.194756],
     [-68.619592, 44.189354],
     [-68.618511, 44.186472],
     [-68.618872, 44.18107],
     [-68.643002, 44.15766],
     [-68.652366, 44.153698],
     [-68.670014, 44.151537],
     [-68.671454, 44.138572],
     [-68.675056, 44.137131],
     [-68.681899, 44.138212],
     [-68.686581, 44.147216],
     [-68.692343, 44.153698],
     [-68.700987, 44.15838],
     [-68.709631, 44.158741],
     [-68.713232, 44.160541],
     [-68.716474, 44.162702],
     [-68.720435, 44.169185],
     [-68.718995, 44.183231],
     [-68.715033, 44.191154],
     [-68.714313, 44.20376],
     [-68.721156, 44.212404],
     [-68.722956, 44.219607],
     [-68.722956, 44.223568],
     [-68.718635, 44.228611],
     [-68.711792, 44.228971],
     [-68.700627, 44.234013],
     [-68.694144, 44.248779],
     [-68.680458, 44.262105],
     [-68.677577, 44.268948],
     [-68.677577, 44.275431],
     [-68.680773, 44.279242]]],
   [[[-68.453236, 44.189998],
     [-68.437789, 44.188216],
     [-68.424441, 44.190753],
     [-68.416434, 44.187047],
     [-68.408207, 44.176298],
     [-68.384903, 44.154955],
     [-68.396634, 44.14069],
     [-68.427534, 44.119266],
     [-68.438518, 44.11618],
     [-68.448646, 44.125581],
     [-68.447505, 44.133493],
     [-68.456813, 44.145268],
     [-68.479934, 44.1478],
     [-68.484696, 44.146495],
     [-68.496639, 44.146855],
     [-68.502096, 44.152388],
     [-68.500817, 44.160026],
     [-68.495511, 44.162429],
     [-68.474365, 44.181875],
     [-68.453236, 44.189998]]],
   [[[-68.358388, 44.125082],
     [-68.35301, 44.127884],
     [-68.346724, 44.127749],
     [-68.330716, 44.110598],
     [-68.331032, 44.10758],
     [-68.338012, 44.101473],
     [-68.365176, 44.101464],
     [-68.376593, 44.112207],
     [-68.376591, 44.113762],
     [-68.375382, 44.11646],
     [-68.365514, 44.124079],
     [-68.358388, 44.125082]]],
   [[[-68.499465, 44.12419],
     [-68.492892, 44.116921],
     [-68.491521, 44.109833],
     [-68.502942, 44.099722],
     [-68.51706, 44.10341],
     [-68.518703, 44.113222],
     [-68.511266, 44.125082],
     [-68.506979, 44.127237],
     [-68.499465, 44.12419]]],
   [[[-68.785601, 44.053503],
     [-68.790595, 44.053832],
     [-68.807315, 44.035796],
     [-68.818441, 44.032046],
     [-68.828465, 44.032118],
     [-68.862845, 44.025037],
     [-68.874139, 44.025359],
     [-68.889717, 44.032516],
     [-68.899997, 44.06696],
     [-68.905098, 44.077344],
     [-68.913406, 44.08519],
     [-68.907812, 44.105518],
     [-68.908984, 44.110001],
     [-68.943105, 44.10973],
     [-68.944597, 44.11284],
     [-68.935327, 44.13038],
     [-68.917286, 44.148239],
     [-68.888597, 44.15955],
     [-68.87868, 44.166612],
     [-68.847249, 44.183017],
     [-68.825067, 44.186338],
     [-68.819156, 44.180462],
     [-68.822206, 44.178815],
     [-68.82284, 44.173693],
     [-68.818423, 44.160978],
     [-68.792221, 44.145998],
     [-68.786886, 44.143961],
     [-68.782375, 44.14531],
     [-68.780693, 44.143274],
     [-68.792065, 44.136759],
     [-68.802162, 44.137857],
     [-68.818039, 44.136852],
     [-68.819659, 44.135434],
     [-68.820515, 44.130198],
     [-68.81953, 44.122056],
     [-68.815562, 44.115836],
     [-68.806832, 44.116339],
     [-68.790525, 44.09292],
     [-68.781772, 44.084274],
     [-68.772639, 44.078439],
     [-68.77029, 44.069566],
     [-68.77965, 44.057754],
     [-68.785601, 44.053503]]],
   [[[-68.618212, 44.012367],
     [-68.635315, 44.018886],
     [-68.64736, 44.0145],
     [-68.651863, 44.009859],
     [-68.652881, 44.003845],
     [-68.657031, 44.003823],
     [-68.659972, 44.016013],
     [-68.659874, 44.022758],
     [-68.657369, 44.024404],
     [-68.650767, 44.039908],
     [-68.654783, 44.059599],
     [-68.661594, 44.075837],
     [-68.627893, 44.088128],
     [-68.62535, 44.092906],
     [-68.6181, 44.096706],
     [-68.609722, 44.094674],
     [-68.602863, 44.08665],
     [-68.589563, 44.075585],
     [-68.585916, 44.075335],
     [-68.584074, 44.070578],
     [-68.588098, 44.06127],
     [-68.590792, 44.058662],
     [-68.601099, 44.058362],
     [-68.611473, 44.025176],
     [-68.610703, 44.013422],
     [-68.615896, 44.009761],
     [-68.618212, 44.012367]]],
   [[[-69.043981, 44.005684],
     [-69.047583, 44.002283],
     [-69.052309, 43.996324],
     [-69.05498, 43.993858],
     [-69.064021, 43.992009],
     [-69.069569, 43.985022],
     [-69.0782, 43.974132],
     [-69.092994, 43.979063],
     [-69.096899, 43.981324],
     [-69.093816, 43.984611],
     [-69.08683, 43.987077],
     [-69.077172, 43.990159],
     [-69.068336, 43.995502],
     [-69.061966, 44.000023],
     [-69.058679, 44.00331],
     [-69.058268, 44.007625],
     [-69.062172, 44.010297],
     [-69.066693, 44.008653],
     [-69.071624, 44.00742],
     [-69.07183, 44.012557],
     [-69.061966, 44.015023],
     [-69.047583, 44.013995],
     [-69.043981, 44.005684]]],
   [[[-69.42792, 43.928798],
     [-69.423323, 43.922871],
     [-69.422153, 43.917702],
     [-69.423324, 43.915507],
     [-69.438066, 43.909539],
     [-69.440913, 43.909767],
     [-69.441894, 43.916331],
     [-69.433762, 43.949353],
     [-69.429806, 43.948438],
     [-69.421072, 43.938261],
     [-69.42792, 43.928798]]],
   [[[-68.880242, 43.863398],
     [-68.882554, 43.848525],
     [-68.876224, 43.836597],
     [-68.886725, 43.822195],
     [-68.898319, 43.820987],
     [-68.899108, 43.821925],
     [-68.893537, 43.831498],
     [-68.8947, 43.84397],
     [-68.898045, 43.849545],
     [-68.903957, 43.848684],
     [-68.908222, 43.849852],
     [-68.902618, 43.868855],
     [-68.889367, 43.87553],
     [-68.880242, 43.863398]]],
   [[[-69.307908, 43.773767],
     [-69.306751, 43.775095],
     [-69.302995, 43.774591],
     [-69.300376, 43.772144],
     [-69.300818, 43.768599],
     [-69.314325, 43.756707],
     [-69.322559, 43.755883],
     [-69.323569, 43.758994],
     [-69.321141, 43.765763],
     [-69.313631, 43.772762],
     [-69.307908, 43.773767]]],
   [[[-70.119671, 43.748621],
     [-70.113059, 43.74913],
     [-70.097318, 43.757292],
     [-70.094986, 43.753211],
     [-70.100233, 43.742134],
     [-70.107812, 43.734555],
     [-70.109561, 43.730474],
     [-70.108978, 43.722312],
     [-70.124136, 43.70832],
     [-70.129383, 43.70832],
     [-70.138128, 43.718231],
     [-70.138711, 43.727559],
     [-70.127051, 43.742717],
     [-70.119671, 43.748621]]],
   [[[-70.087621, 43.699913],
     [-70.093704, 43.6918],
     [-70.099594, 43.695366],
     [-70.115908, 43.682978],
     [-70.118291, 43.683343],
     [-70.118174, 43.686375],
     [-70.115961, 43.689202],
     [-70.100683, 43.705962],
     [-70.095727, 43.709278],
     [-70.093113, 43.710524],
     [-70.092137, 43.709468],
     [-70.097184, 43.700929],
     [-70.091929, 43.698111],
     [-70.087621, 43.699913]]],
   [[[-70.163884, 43.692404],
     [-70.156787, 43.694706],
     [-70.146115, 43.701635],
     [-70.135563, 43.700658],
     [-70.154503, 43.680933],
     [-70.168227, 43.675136],
     [-70.170284, 43.675441],
     [-70.173571, 43.683734],
     [-70.171339, 43.687546],
     [-70.163884, 43.692404]]],
   [[[-70.186213, 43.682655],
     [-70.187536, 43.678669],
     [-70.192574, 43.673139],
     [-70.207341, 43.662562],
     [-70.210825, 43.661695],
     [-70.21313, 43.662973],
     [-70.213948, 43.666161],
     [-70.209627, 43.676308],
     [-70.201893, 43.685483],
     [-70.196535, 43.688784],
     [-70.191041, 43.689071],
     [-70.186213, 43.682655]]],
   [[[-70.171245, 43.663498],
     [-70.171136, 43.6633],
     [-70.190323, 43.642986],
     [-70.205934, 43.633633],
     [-70.207165, 43.63369],
     [-70.211062, 43.641842],
     [-70.200116, 43.662978],
     [-70.188047, 43.673762],
     [-70.184659, 43.674699],
     [-70.171245, 43.663498]]],
   [[[-70.703819, 43.059825],
     [-70.704696, 43.070989],
     [-70.705996, 43.073089],
     [-70.708896, 43.074989],
     [-70.720296, 43.074688],
     [-70.733497, 43.073288],
     [-70.737897, 43.073488],
     [-70.741897, 43.077388],
     [-70.756397, 43.079988],
     [-70.757597, 43.080888],
     [-70.762997, 43.089488],
     [-70.766398, 43.092688],
     [-70.767998, 43.093588],
     [-70.779098, 43.095887],
     [-70.78388, 43.100867],
     [-70.793906, 43.106712],
     [-70.808708, 43.117065],
     [-70.82, 43.122586],
     [-70.8268, 43.127086],
     [-70.8281, 43.129086],
     [-70.8293, 43.132486],
     [-70.83, 43.138386],
     [-70.8329, 43.143286],
     [-70.8338, 43.146886],
     [-70.829101, 43.157886],
     [-70.827801, 43.166385],
     [-70.828301, 43.168985],
     [-70.826201, 43.172085],
     [-70.824001, 43.173285],
     [-70.823501, 43.174585],
     [-70.824801, 43.179685],
     [-70.828301, 43.186685],
     [-70.827901, 43.188685],
     [-70.827201, 43.189485],
     [-70.823754, 43.191075],
     [-70.820702, 43.191663],
     [-70.819344, 43.193036],
     [-70.819146, 43.195157],
     [-70.820366, 43.197629],
     [-70.820763, 43.19978],
     [-70.816903, 43.214604],
     [-70.816033, 43.21568],
     [-70.813119, 43.217252],
     [-70.80967, 43.224561],
     [-70.80964, 43.225407],
     [-70.811852, 43.228306],
     [-70.814019, 43.229053],
     [-70.815453, 43.229023],
     [-70.816232, 43.234997],
     [-70.817773, 43.237408],
     [-70.817865, 43.237911],
     [-70.822959, 43.240187],
     [-70.823309, 43.240343],
     [-70.825071, 43.24093],
     [-70.826711, 43.241301],
     [-70.828022, 43.241597],
     [-70.83365, 43.242868],
     [-70.837274, 43.242321],
     [-70.838678, 43.242931],
     [-70.841273, 43.248653],
     [-70.841059, 43.249699],
     [-70.839717, 43.250393],
     [-70.839213, 43.251224],
     [-70.843302, 43.254321],
     [-70.852015, 43.256808],
     [-70.855082, 43.255191],
     [-70.858207, 43.256286],
     [-70.859607, 43.257342],
     [-70.859853, 43.259763],
     [-70.861384, 43.263143],
     [-70.863231, 43.265098],
     [-70.86323, 43.265109],
     [-70.872585, 43.270152],
     [-70.881704, 43.272483],
     [-70.882804, 43.273183],
     [-70.883704, 43.277483],
     [-70.886504, 43.282783],
     [-70.890204, 43.284182],
     [-70.896304, 43.285282],
     [-70.906005, 43.291682],
     [-70.907405, 43.293582],
     [-70.903905, 43.296882],
     [-70.90139, 43.298764],
     [-70.900386, 43.301358],
     [-70.90231, 43.304872],
     [-70.904485, 43.30529],
     [-70.907405, 43.304782],
     [-70.909805, 43.306682],
     [-70.91246, 43.308289],
     [-70.911625, 43.309952],
     [-70.912004, 43.319821],
     [-70.915406, 43.319858],
     [-70.916421, 43.320279],
     [-70.923949, 43.324768],
     [-70.930783, 43.329569],
     [-70.931641, 43.331019],
     [-70.932198, 43.33456],
     [-70.932735, 43.33676],
     [-70.93711, 43.337367],
     [-70.951525, 43.334672],
     [-70.953034, 43.333257],
     [-70.956528, 43.334691],
     [-70.95786, 43.337776],
     [-70.960439, 43.341048],
     [-70.964028, 43.341888],
     [-70.967229, 43.343777],
     [-70.974863, 43.357969],
     [-70.974156, 43.362925],
     [-70.976408, 43.367272],
     [-70.981859, 43.373862],
     [-70.984335, 43.376128],
     [-70.984305, 43.376814],
     [-70.985965, 43.380023],
     [-70.985958, 43.38424],
     [-70.985205, 43.386745],
     [-70.987649, 43.389521],
     [-70.987733, 43.391513],
     [-70.98739, 43.393457],
     [-70.982876, 43.394808],
     [-70.982565, 43.39778],
     [-70.982817, 43.399312],
     [-70.985767, 43.40162],
     [-70.986677, 43.403541],
     [-70.987249, 43.411863],
     [-70.986812, 43.414264],
     [-70.982898, 43.419332],
     [-70.978052, 43.421954],
     [-70.97462, 43.423022],
     [-70.971039, 43.425606],
     [-70.968359, 43.429283],
     [-70.969362, 43.432731],
     [-70.968782, 43.434891],
     [-70.96115, 43.438321],
     [-70.961046, 43.440475],
     [-70.96164, 43.443039],
     [-70.96581, 43.447557],
     [-70.9669, 43.450458],
     [-70.966266, 43.453627],
     [-70.96399, 43.456752],
     [-70.96045, 43.466592],
     [-70.961428, 43.469696],
     [-70.964433, 43.473276],
     [-70.964542, 43.473262],
     [-70.966017, 43.472918],
     [-70.970946, 43.4739],
     [-70.972956, 43.47502],
     [-70.974245, 43.47742],
     [-70.967968, 43.480783],
     [-70.967404, 43.482635],
     [-70.968975, 43.483961],
     [-70.969572, 43.486201],
     [-70.966718, 43.491278],
     [-70.961948, 43.49775],
     [-70.959185, 43.499351],
     [-70.957958, 43.508041],
     [-70.954755, 43.509802],
     [-70.955386, 43.511357],
     [-70.956856, 43.512719],
     [-70.954045, 43.518797],
     [-70.954066, 43.52261],
     [-70.956787, 43.524216],
     [-70.957214, 43.524994],
     [-70.957046, 43.528743],
     [-70.95822, 43.531586],
     [-70.962556, 43.53431],
     [-70.963342, 43.535247],
     [-70.963531, 43.536756],
     [-70.963281, 43.538929],
     [-70.962182, 43.541032],
     [-70.955928, 43.541925],
     [-70.955337, 43.54098],
     [-70.955252, 43.540887],
     [-70.950838, 43.551026],
     [-70.951876, 43.552238],
     [-70.953322, 43.552718],
     [-70.955017, 43.554239],
     [-70.95586, 43.559787],
     [-70.957234, 43.561358],
     [-70.961848, 43.562964],
     [-70.968546, 43.568856],
     [-70.970124, 43.568544],
     [-70.972716, 43.570255],
     [-70.975705, 43.625078],
     [-70.981946, 43.70096],
     [-70.981978, 43.701965],
     [-70.982238, 43.711865],
     [-70.982083, 43.715043],
     [-70.984901, 43.752983],
     [-70.989067, 43.79244],
     [-70.989929, 43.839239],
     [-70.992653, 43.89624],
     [-70.992842, 43.916269],
     [-70.998444, 44.041099],
     [-71.001367, 44.092931],
     [-71.001335, 44.093205],
     [-71.008567, 44.245491],
     [-71.008764, 44.258443],
     [-71.008736, 44.258825],
     [-71.01127, 44.301846],
     [-71.012749, 44.340784],
     [-71.015363, 44.378113],
     [-71.020773, 44.473737],
     [-71.022992, 44.500058],
     [-71.026655, 44.558149],
     [-71.031039, 44.655455],
     [-71.036705, 44.736498],
     [-71.037518, 44.755607],
     [-71.044646, 44.845039],
     [-71.052707, 44.93084],
     [-71.057861, 45.000049],
     [-71.059004, 45.004918],
     [-71.069387, 45.144037],
     [-71.0726, 45.180935],
     [-71.076914, 45.246912],
     [-71.084334, 45.305293],
     [-71.078407, 45.306232],
     [-71.073743, 45.307718],
     [-71.066197, 45.311353],
     [-71.059265, 45.313753],
     [-71.042485, 45.313043],
     [-71.03821, 45.311922],
     [-71.030565, 45.312652],
     [-71.021753, 45.314409],
     [-71.014268, 45.316761],
     [-71.00905, 45.319022],
     [-71.002563, 45.327819],
     [-71.0024, 45.328482],
     [-71.005087, 45.331545],
     [-71.011144, 45.334679],
     [-71.01292, 45.343297],
     [-71.012757, 45.34476],
     [-71.01081, 45.34725],
     [-71.004848, 45.345419],
     [-71.001771, 45.343658],
     [-70.99273, 45.338173],
     [-70.990233, 45.336277],
     [-70.989324, 45.334655],
     [-70.985595, 45.332188],
     [-70.967188, 45.332401],
     [-70.950824, 45.33453],
     [-70.949365, 45.331536],
     [-70.943887, 45.324336],
     [-70.939188, 45.320177],
     [-70.929923, 45.318462],
     [-70.921435, 45.313867],
     [-70.917904, 45.311924],
     [-70.912111, 45.296197],
     [-70.913732, 45.292746],
     [-70.918753, 45.287033],
     [-70.919951, 45.284953],
     [-70.9217, 45.279445],
     [-70.921474, 45.278873],

In [31]:
with open('state_car_info.json', 'w') as fp:
    json.dump(datastore, fp)